travis:
  secure:
    BINSTAR_TOKEN: GCoAOtX3BJyzqOCTbbCvh7Ojwem0yuUVW1lAOYEh+1k7p19Bq930bE7A7fQdsgUqEgnkeq38bTVSPgf6Tv4Vzwhpfto9OlojXFZzxZwimxDZ9kZvmDoqtlIICtYe44AZpZBYnTKcL1lYT7QIjar3SPvWkXetr/GzYD8PhYT4+yESt6mopfd1X+AgpJv1DBmjO17hqVkeO1vyMZn41vE4ijt6rZmp1bNkSPBYBHYMlN/i5yCvY5wSeEcYjbya0qFmpPTfJMfF3FzT7KtVO/cn2G0uJ+DY6tFlpBDRwq/0ULmO+FMVlAp1AVHRPgYoN9GeeTeUbbnw1OP8azX1JDvD7erZ6RZLDugk4kLUge6y/q9EVbXvYbvnM72x0PpiYItqz9Wo/Ljql7CEc/pTV0gIuildbu1zGIM/zdDd2awRKokJabdgaLWDM8kaZiWJMcgi3BSnnDiwa2/iyof8Ku0bktU5ED+Qu60hSjadBlRb1f364jQnqJQMiIqsfY3CsLz6kEbiDoV2ShqCtUcVvTHWvPzb4xrfwqeXANjoKZQIWNoWY4ORhScWK6yFqYYg1n6DTvBUEAmCivAwWduA+tOu8zSE5b4zsqUUGbmzZxQMGklHVPjIVSvZtT0vOp0wF45LbZhuk4D8H3wENBX3hk5VjPefnoCb1nNiOm3ExN7ncRc=
appveyor:
  secure:
    BINSTAR_TOKEN: ipv/06DzgA7pzz2CIAtbPxZSsphDtF+JFyoWRnXkn3O8j7oRe3rzqj3LOoq2DZp4
