travis:
  secure:
    BINSTAR_TOKEN: ETC/CDZ9xfE247F+0f4+EaACJaokJqy7QBQnQHpbX2pNLeioqkiOGzY98zFgaCg8Hfxf6xRagZST6IA6XCG2QJ/gGOQ4QTyFatJz0Sdit52ykij3O91/kfT8iIeVba/oaiNL77GgkEU65qZMWAiiuL78Y6yenoVtcb+Y/dFdEa0rkdsK5m+QFRkR9Raw5TBOLPe76aSlJzCEHKutRoEMx2IAkCaeFZh9DZxLb61xT7CZ4LBrCEgSDy47hxy3+SMFizl5utDDTvTJLjCb+v28d2/7binL3+e/eYvx/o0gOUUhyV3oXoezbvHJDkDZ9d4o/4xAytHU6pTPYgy2Mt2Af3k7B9gc2MoizoS3Tlu5/Tclyf3RdQZ7ox8wzj1xxXoK1zzrPCMRMnPk5r2RdUXK1mggHwlpMoP/43Y7gHz0NldTgdO/L/LdAmcV/N8aYdwhDrTtEnyBvS2IAPwr01ejzRPty5to5t8FM9dw0Zmf8GwGQXWZn2PdFdwKV/eGnII97zFjGC4FUTy0bq2CJFya9wWoix/GBftCUYb/qZcBfEiCEXqYqRUVu9AEZ110ZZ6eJDOwnY0CbD3GyG2b7vZ2bjRV8LxxaQtDn9LgasktqByCi58fgR2Vmt/TZ/x7yVS5tqDzYIik6n905um5bed+73CpfE9ZCWPajxjgo4yyflI=
appveyor:
  secure:
    BINSTAR_TOKEN: ipv/06DzgA7pzz2CIAtbPxZSsphDtF+JFyoWRnXkn3O8j7oRe3rzqj3LOoq2DZp4
